### ISSUE TITLE
Fix documentation syntax

### ISSUE THREAD

**Issue by cthoyt** [cebel/pyuniprot#17]
https://github.com/cebel/pyuniprot/blob/6bb0045cdd71199d0713400ad35c4bdd08f550b1/src/pyuniprot/manager/query.py#L195-L215

each of these instances where it can be multiple things can should be written as

`:param str or tuple[str] name: UniProt entry name(s) `, etc.

If we ever get awesome and write Python 3.6+ only code, we can use real type annotations too :)

**Comment by cebel** [comment]
Can you please specify a reference to this style of documentation. Because this ends up with ugly Sphinx documentation as:

or tuple[str] name (str)

**Comment by cebel** [comment]
Found it
https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions

but it's different, should be:

        :param name: UniProt entry name(s)
        :type name: str or tuple[str]

**Comment by cebel** [comment]
See Sphinx doc...

http://www.sphinx-doc.org/en/stable/domains.html

    :type point: tuple(float, float)
    :type point: tuple[float, float]

tuple can use () or []. I like more () because more intuitive for tuples

Will change query docs now to:

    :param name: UniProt entry name(s)
    :type name: str or tuple(str) or None
