### ISSUE TITLE
Add EC Hierarchy Table

### ISSUE THREAD

**Issue by cthoyt** [cebel/pyuniprot#7]
This table should contain information about the hierarchy underlying the ECNumber table. 

If this information isn't available in UniProt, then we might have to write a parser (perhaps also as a separate package) for ftp://ftp.expasy.org/databases/enzyme/enzclass.txt and match them

**Comment by cebel** [comment]
ftp://ftp.expasy.org/databases/enzyme/enzyme.dat is the right place (ugly old dat format). Close this, because this content for PyEnzyme ;-).
